[package]
name = "mycelium-async"
version = "0.1.0"
edition = "2021"
authors = [
    "Eliza Weisman <eliza@elizas.website>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mycelium-util = { path = "../util" }
cordyceps = { path = "../cordyceps" }

[dependencies.tracing]
default_features = false
features = ["attributes"]
git = "https://github.com/tokio-rs/tracing"

[dev-dependencies]
loom = "0.5.2"