[package]
name = "hal-x86_64"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@elizas.website>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal-core = { path = "../hal-core" }
mycelium-util = { path = "../util" }
lazy_static = { version = "1.4", features = ["spin_no_std"]}
